server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qweasd123
mybatis:
  mapper-locations:
    classpath: mapper/*.xml      # 扫描所有mybatis中的xml文件   *表示 所有 all
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出日志log 也就是sql语句